# Generated by Django 4.2.4 on 2023-08-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField()),
                ("temperature", models.FloatField()),
                ("humidity", models.FloatField()),
                ("soil_moisture", models.FloatField()),
                ("light_intensity", models.FloatField()),
                ("rainfall", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("farm", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="farm_portal.farm")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
