# Generated by Django 4.2.4 on 2023-08-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
           name="Farm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("farm_name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("size_acres", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user_portal.user")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
